### If the program should monitor hosts, set MONITOR_HOSTS to true
MONITOR_HOSTS: true
# The port the receiver runs on
RECEIVE_PORT: "8758"
# How often the system checks if it is time to send a report
AGGREGATE_PERIOD: "60"
# The hour the report is sent
AGGREGATE_HOUR: "1"
# How long should the receiver wait for a host report before trying to ping
EXPECTED_REPORT_PERIOD: "1"
# The port to access GQL playground on server
GQL_PORT: "8081"
# The address and port of the custom API
API_IP: "127.0.0.1"
API_PORT: "4100"
API_REPORT: "/api/towerreport"
API_ALERT: "/api/alert/"
# What is the MQTT broker to subscribe to
MQTT_BROKER: "tcp://127.0.0.1:1883"
MQTT_TOPIC: "test"

### If the program should monitor a testbed via ping, set MONITOR_TESTBED to true
MONITOR_TESTBED: false
# Provide the IP address of the testbed to be monitored
TESTBED_IP: "1.1.1.1"
# How often the testbed should be pinged
PING_PERIOD: "30"