# The port the receiver runs on
RECEIVE_PORT: "8758"
# How often the system checks if it is time to send a report
AGGREGATE_PERIOD: "60"
# The hour the report is sent
AGGREGATE_HOUR: "23"
# How long should the receiver wait for a host report before trying to ping
EXPECTED_REPORT_PERIOD: "1"