// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HostStatus struct {
	ID           string `json:"id"`
	BoardReached string `json:"board_reached"`
	TowerReached string `json:"tower_reached"`
	BootTime     string `json:"boot_time"`
	Reboots      int    `json:"reboots"`
	UsedRAM      string `json:"used_ram"`
	UsedDisk     string `json:"used_disk"`
	CPU          string `json:"cpu"`
	Reachable    bool   `json:"reachable"`
	Temperature  string `json:"temperature"`
}
